### ISSUE TITLE
Shell-command issue with escaping on Windows

### ISSUE THREAD

**Issue by alvatar** [feeley/gambit#122] opened 2015-05-07 12:02 UTC
The following code:
```
(shell-command (path-expand "~~/bin/gsc"))
```
produces:
```
sh: C:/MinGW/msys/1.0/local/Gambit-Cbin/gsc: No such file or directory
```
on Windows, while it runs successfully on Linux/OSX.

**Comment by feeley** [comment] 2015-05-07 13:20
What is returned by (path-expand "~~/bin/gsc") and (path-expand "~~bin/gsc") ?

**Comment by feeley** [comment] 2015-05-07 13:24
Lets try that again... What is returned by `(path-expand "~~/bin/gsc")` and `(path-expand "~~bin/gsc")` and `(path-expand "~~")` and `(current-directory)` ?

**Comment by alvatar** [comment] 2015-05-07 14:37
(path-expand "~~/bin/gsc")
"C:/MinGW/msys/1.0/local/Gambit-C\\bin/gsc"
(path-expand "~~bin/gsc")
"C:/MinGW/msys/1.0/local/Gambit-C\\bin\\gsc"
(path-expand "~~") 
"C:/MinGW/msys/1.0/local/Gambit-C\\"
(current-directory)
"C:\\MinGW\\msys\\1.0\\home\\Alvaro\\"

**Comment by feeley** [comment] 2015-05-07 14:43
That's interesting.  You are mixing paths with / and \ .  How did you configure Gambit?

**Comment by alvatar** [comment] 2015-05-07 14:48
Plain and simple ./configure, nothing more

**Comment by feeley** [comment] 2015-05-07 15:03
So the problem is that the configure script is introducing Unix-like paths when it should generate Windows-like paths.  Can you try forcing the installation path with ./configure --prefix=C:\\aaa\\bbb ?  I'll check what the configure script is doing.

**Comment by alvatar** [comment] 2015-05-07 15:37
I can see a horrible thing going on during the make process at the output:

With
```
 ./configure --prefix=C:\\MinGW\\msys\\1.0\\local\\Gambit-C
```

```
gcc -D_WINDOWS -D_WIN32_WINNT=0x0502  -Wno-unused -Wno-write-strings -O1 -fno-math-errno -fschedule-insns2 -fno-strict-aliasing -fno-trapping-math -fwrapv -fno-keep-inline-dllexport -fno-common -mieee-fp   -I"../include" -c -o "os_time.o" -I. -DHAVE_CONFIG_H -D___GAMBCDIR="\"C:\MinGW\msys\1.0\local\Gambit-C\"" -D___SYS_TYPE_CPU="\"i686\"" -D___SYS_TYPE_VENDOR="\"pc\"" -D___SYS_TYPE_OS="\"mingw32\"" -D___CONFIGURE_COMMAND="\"./configure '--prefix=C:\\\\\\\\MinGW\\\\\\\\msys\\\\\\\\1.0\\\\\\\\local\\\\\\\\Gambit-C'"\" -D___OBJ_EXTENSION="\".o\"" -D___EXE_EXTENSION="\".exe\"" -D___BAT_EXTENSION="\".bat\"" -D___PRIMAL os_time.c -D___LIBRARY
```

Otherwise:
```
$ ./configure --prefix=C:\MinGW\msys\1.0\local\Gambit-C
configure: error: expected an absolute directory name for --prefix: C:MinGWmsys1.0localGambit-C
```

**Comment by alvatar** [comment] 2015-05-07 15:39
My workaround is summarized in this:

``` scheme
-(define gambit-compiler (make-parameter
-                        ;; This append fixes an issue with MinGW paths
-                        (string-append (path-expand "~~") "/bin/gsc")))
+(define gambit-compiler (make-parameter (path-expand "~~/bin/gsc")))

 (define c-compiler (make-parameter "gcc"))
```

**Comment by gcartier** [comment] 2015-05-07 15:54
The solution I've been using for a long time is to figure out (black magic)
where to use c:/ or /c/ syntaxes.

With configure it's the later. For example I do:
./configure --prefix=/c/App/gambit and everything works fine.

**Comment by feeley** [comment] 2015-05-07 20:08
Please try again with the latest commit...

**Comment by feeley** [comment] 2015-05-07 20:09
You also might want to try ./configure --prefix="C:\\some path\\foo\\bar"

**Comment by feeley** [comment] 2015-05-07 20:09
with doubled backslashes (or maybe quadrupled)

**Comment by alvatar** [comment] 2015-05-10 17:28
Is this pending? Should I try it?

**Comment by feeley** [comment] 2015-05-26 04:07
As far as I can tell the problem is now fixed.

**Closed by feeley** 2015-05-26 04:07 UTC
